### ISSUE TITLE
Amazon rejected...

### ISSUE THREAD

**Issue by d0wNjumper** [dstuecken/Amazon-WD-Alerts#1]
hello,

im getting this message after starting the "program" : Damn, Amazon rejected our request. Retrying in five seconds. But first i get the normal message, that the deal is available .. after sleeping 30 sec i will get the reject error.

**Comment by dstuecken** [comment]
Yea this is because Amazon is detecting the script as a possible bot and shows a capture image.

Do you have the php curl extension enabled? This way the script uses cookies which could help since it almost reacts like a browser. Maybe Amazon is not rejecting that quick then. You just need to install and enable php_curl and restart the script, theres no further configuration is needed.

**Comment by abgut44** [comment]
Hi ! first of all thanks for sharing... really awesome. I have a question, I have knowledge about HTML CSS, a bit of php, but not that much. I am using windows, and trying to use your script.  Never used the command line on windows, .. Could you maybe give me some noob tipps.. Something like step by step ( thannnnnks)

**Comment by dstuecken** [comment]
1) Download the Tool https://github.com/dstuecken/Amazon-WD-Alerts/releases/download/1.0.2/amazon-wd-alerts.zip and extract it into c:\

Then download php from http://windows.php.net/downloads/releases/php-5.6.29-nts-Win32-VC11-x86.zip, then extract it to c:\amazon-wd-alerts, then open your console and type the following

c:
cd amazon-wd-alerts
php.exe check.php B01BWAHNH4

**Comment by abgut44** [comment]
Hello, thank you for your answer,  it worked but not 100 %, getting this error message : " Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01WAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312" 

Think it hast something to do with PHP environment ? Regards

**Comment by dstuecken** [comment]
Yes, rename php.ini-production to php.ini in your c:\amazon-wd-alerts directory. Them open the php.ini file and remove the ; from ;extension=php_openssl.dll, so it looks like this:

`...
;extension=php_oci8_12c.dll  ; Use with Oracle Database 12c Instant Client
extension=php_openssl.dll
;extension=php_pdo_firebird.dll
...`

**Comment by abgut44** [comment]
Good morning, thanks again for trying to help me, but it is still not working. 
I am connected to the internet via LAN, and yeah that is all. I've done what you have told me, If you still have any other idea it would be great, here are the error messages (thanks)

C:\amazon-wd-alerts>php.exe check.php B01BWAHNH4
The system cannot find the path specified.
I'm happy to start scanning for your deals!
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
Error creating resource: [message] fopen(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP?
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312
[message] fopen(https://www.amazon.de/gp/offer-listing/B01BWAHNH4): failed to open stream: Invalid argument
[file] C:\amazon-wd-alerts\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php
[line] 312

**Comment by dstuecken** [comment]
Please try again with this PHP configuration: [php.ini.zip](https://github.com/dstuecken/Amazon-WD-Alerts/files/684376/php.ini.zip)

Extract into your C:\amazon-wd-alerts directory.

It has something to do with your ssl extension. It is not loaded properly.

**Comment by abgut44** [comment]
Hey ! again thanks to triyng to figure it out, hopefully, you like to fix stuff 👍  
So, I am on my private machine at home, when I do here the first tutorial what you have explained, I will get this error message : C:\>cd c:\amazon-wd-alerts

c:\amazon-wd-alerts>php.exe check.php B01BWAHNH4

Warning: require(C:\amazon-wd-alerts\vendor\composer/../symfony/polyfill-mbstring/bootstrap.php): failed to open stream: No such file or directory in C:\amazon-wd-alerts\vendor\composer\autoload_real.php on line 66

Fatal error: require(): Failed opening required 'C:\amazon-wd-alerts\vendor\composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='.;C:\php\pear') in C:\amazon-wd-alerts\vendor\composer\autoload_real.php on line 66

c:\amazon-wd-alerts>


doing normal tutorial 

the other one with prepared folder



When doing the changes, and adding the PHP file which you have created or added for me, then I will get this error message : 
c:\amazon-wd-alerts>php.exe check.php B01BWAHNH4
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\php\ext\php_curl.dll' - Das angegebene Modul wurde nicht gefunden.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'C:\php\ext\php_curl.dll' - Das angegebene Modul wurde nicht gefunden.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\php\ext\php_openssl.dll' - Das angegebene Modul wurde nicht gefunden.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'C:\php\ext\php_openssl.dll' - Das angegebene Modul wurde nicht gefunden.
 in Unknown on line 0
PHP Warning:  require(C:\amazon-wd-alerts\vendor\composer/../symfony/polyfill-mbstring/bootstrap.php): failed to open stream: No such file or directory in C:\amazon-wd-alerts\vendor\composer\autoload_real.php on line 66

Warning: require(C:\amazon-wd-alerts\vendor\composer/../symfony/polyfill-mbstring/bootstrap.php): failed to open stream: No such file or directory in C:\amazon-wd-alerts\vendor\composer\autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required 'C:\amazon-wd-alerts\vendor\composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='.;C:\php\pear') in C:\amazon-wd-alerts\vendor\composer\autoload_real.php on line 66

Fatal error: require(): Failed opening required 'C:\amazon-wd-alerts\vendor\composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='.;C:\php\pear') in C:\amazon-wd-alerts\vendor\composer\autoload_real.php on line 66

Good night :)
