### ISSUE TITLE
Notification only at defined price

### ISSUE THREAD

**Issue by blautob** [dstuecken/Amazon-WD-Alerts#2]
Hi Dennis

Great tool so far!
Do you think it is possible to implement afeature to only get a notigication if a product has a specific price?

Best regards

**Comment by dstuecken** [comment]
Good idea, just implemented that and created new version 1.0.4 :)

You can now add the price as a second argument:

```shell
cd Amazon-WD-Alerts
c:/path/to/php.exe check.php B01BWAHNH4 299,99
```
