### ISSUE TITLE
error parsing Amazons website

### ISSUE THREAD

**Issue by celevra** [dstuecken/Amazon-WD-Alerts#5]
Hi,

by checking this product:
https://www.amazon.de/gp/product/B001A2H050

i get folowing error:
```
amazon-wd-alerts # ./check.sh B001A2H050
I'm happy to start scanning for your deals!
Error parsing Amazons website. Please check your article id or engine. (Engine: dstuecken\WdAlerts\Crawler\Amazon; Crawler error: The current node list is empty.)
Error parsing Amazons website. Please check your article id or engine. (Engine: dstuecken\WdAlerts\Crawler\Amazon; Crawler error: The current node list is empty.)
```

i've downloaded the package, but i've also tried with composer, same result
am i doing something wrong?

regards

celevra

**Comment by klabeh** [comment]
change in the src\WdAlerts\Crawler\Amazon\config.yml file

xPathTitle: //div[@id="olpProductDetails"]/div[1]/h1

to

xPathTitle: //div[@id="olpProduct"]/div/div[2]/div/div[2]/h1

**Comment by dstuecken** [comment]
@klabeh would be awesome if you could add this as a PR? :)

**Comment by celevra** [comment]
thank you, but unfortunately it doesn't work.
freshly checked out, installed composer dependencies and run the check against the above mentioned amazon id:
Amazon-WD-Alerts # ./check.sh B001A2H050 29,99
I'm happy to start scanning for your deals!
Server error: `GET https://www.amazon.de/gp/offer-listing/B001A2H050?tag=awdal-21` resulted in a `503 Service Unavailable` response

**Comment by klabeh** [comment]
@celevra 

change the UserAgent in the .config.yml of the home directory and try again

`userAgent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36`

if it works, I like to do a pull request

**Comment by celevra** [comment]
this has helped!
Thank you very much

```
Amazon-WD-Alerts # ./check.sh B001A2H050 29,99
I'm happy to start scanning for your deals!
No deal available at 29. Current best price is EUR 37,71.
Sleeping 30 seconds..
```
